export const WORD_LISTS = [
  {
    id: "base",
    name: "Bàsica",
    words: [
      { key: "gos", emoji: "🐶" },
      { key: "gat", emoji: "🐱" },
      { key: "sol", emoji: "☀️" },
      { key: "sí", emoji: "✅" },
      { key: "no", emoji: "❌" },
      { key: "papa", emoji: "👨" },
      { key: "mama", emoji: "👩" },
      { key: "lluna", emoji: "🌙" },
      { key: "paper", emoji: "📄" },
      { key: "pal", emoji: "🪵" },
      { key: "poma", emoji: "🍎" },
      { key: "kiwi", emoji: "🥝" },
      { key: "plàtan", emoji: "🍌" },
      { key: "menjar", emoji: "🍽️" },
      { key: "pastís", emoji: "🎂" },
      { key: "cotxe", emoji: "🚗" },
      { key: "cor", emoji: "❤️" },
      { key: "avió", emoji: "✈️" },
      { key: "ulls", emoji: "👀" },
      { key: "foc", emoji: "🔥" },
      { key: "serp", emoji: "🐍" },
      { key: "llibre", emoji: "📚" },
      { key: "cuiner", emoji: "👨‍🍳" },
      { key: "llapis", emoji: "✏️" },
      { key: "tissora", emoji: "✂️" },
      { key: "llit", emoji: "🛏️" },
      { key: "bebé", emoji: "👶" },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    words: [
      { key: "gos", emoji: "🐶" },
      { key: "gat", emoji: "🐱" },
      { key: "ocell", emoji: "🐦" },
      { key: "serp", emoji: "🐍" },
      { key: "peix", emoji: "🐟" },
      { key: "vaca", emoji: "🐄" },
      { key: "cavall", emoji: "🐴" },
      { key: "conill", emoji: "🐰" },
      { key: "lleó", emoji: "🦁" },
      { key: "elefant", emoji: "🐘" },
    ],
  },
  {
    id: "casa",
    name: "Casa i escola",
    words: [
      { key: "llit", emoji: "🛏️" },
      { key: "taula", emoji: "🪑" },
      { key: "porta", emoji: "🚪" },
      { key: "llibre", emoji: "📚" },
      { key: "llapis", emoji: "✏️" },
      { key: "paper", emoji: "📄" },
      { key: "tissora", emoji: "✂️" },
      { key: "motxilla", emoji: "🎒" },
      { key: "finestra", emoji: "🪟" },
      { key: "rellotge", emoji: "⏰" },
    ],
  },
  {
    id: "raquel",
    name: "Raquel",
    words: [
      { key: "vaca", emoji: "🐄" },
      { key: "lleó", emoji: "🦁" },
      { key: "maduixa", emoji: "🍓" },
      { key: "sol", emoji: "☀️" },
      { key: "color", emoji: "🎨" },
      { key: "llibreta", emoji: "📓" },
      { key: "obres", emoji: "🚧" },
      { key: "foto", emoji: "📷" },
      { key: "pop", emoji: "🐙" },
      { key: "col", emoji: "🥬" },
      { key: "flor", emoji: "🌸" },
      { key: "nus", emoji: "🪢" },
      { key: "mà", emoji: "✋" },
      { key: "mama", emoji: "👩" },
      { key: "papa", emoji: "👨" },
      { key: "germans", emoji: "👬" },
      { key: "aigua", emoji: "💧" },
      { key: "fulla", emoji: "🍃" },
      { key: "paper", emoji: "📄" },
      { key: "llapis", emoji: "✏️" },
      { key: "piano", emoji: "🎹" },
      { key: "ou", emoji: "🥚" },
      { key: "pingüí", emoji: "🐧" },
      { key: "mitjó", emoji: "🧦" },
    ],
  },
];
